import Chatwidget from "@/components/chatbot_new";
import "./globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Chatwidget />
      </body>
    </html>
  );
}
